const ALL_ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
}

const ORDER_STATUS_CAN_BE_CANCELLED = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED'
}

const ORDER_STATUS_CAN_NOT_CANCELLED = {
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
}

export { ALL_ORDER_STATUS, ORDER_STATUS_CAN_NOT_CANCELLED, ORDER_STATUS_CAN_BE_CANCELLED }